version: "3.8"

services:
  webizly:
    build: .
    container_name: webizly-production
    pull_policy: always
    restart: always
    networks:
       - traefik
       - backend
    ports:
      - "80"
    environment:
      - DEPLOYMENT=production
      - DATABASE_URL=postgresql+psycopg2://production:production@postgres:5432/production
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "production"
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.webizly.rule=Host(`www.salmaanweb.xyz`) || Host(`salmaanweb.xyz`)
      - traefik.http.routers.webizly.entrypoints=https
      - traefik.http.routers.webizly.tls=true
      - traefik.http.routers.webizly.tls.certresolver=simple-resolver
      - traefik.http.services.webizly.loadbalancer.server.port=80
networks:
  traefik:
      name: traefik
      external: true
  backend:
      name: backend
      external: true
