version: "3.8"

services:
  postgres:
    build: .
    container_name: postgres
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
networks:
  backend:
      external: true
